### ISSUE TITLE
miui获取相机图片崩溃

### ISSUE THREAD

**Issue by yiflylian** [wj576038874/PhotoSelector#2]
10-18 09:13:17.574 20078-20078/com.bjcathay.xiaoniu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bjcathay.xiaoniu, PID: 20078
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1002, result=-1, data=null} to activity {com.bjcathay.xiaoniu/com.winfo.photoselector.ImageSelectorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4196)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
        at com.winfo.photoselector.ImageSelectorActivity.geturi(ImageSelectorActivity.java:785)
        at com.winfo.photoselector.ImageSelectorActivity.onActivityResult(ImageSelectorActivity.java:607)
        at android.app.Activity.dispatchActivityResult(Activity.java:7116)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4192)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6365) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
10-18 09:13:17.574 2137-2137/? E/Icon: Unable to load resource 0x00000000 from pkg=com.android.systemui
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:201)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
        at android.content.res.Resources.getDrawable(Resources.java:784)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:316)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:272)
        at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:380)
        at com.android.systemui.statusbar.ExpandedIcon.getDrawable(ExpandedIcon.java:59)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:195)
        at com.android.systemui.statusbar.StatusBarIconView.setIcon(StatusBarIconView.java:142)
        at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:109)
        at com.android.systemui.statusbar.phone.SimpleStatusBar.updateIcon(SimpleStatusBar.java:278)
        at com.android.systemui.statusbar.phone.PhoneStatusBar.updateIcon(PhoneStatusBar.java:2468)
        at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:455)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)

**Comment by yiflylian** [comment]
注释掉ImageModel 类中 （loadImageForSDCard） 56行何58行 得以解决 。代码如下
 56  //    if (!".downloading".equals(getExtensionName(path))) { //过滤未下载完成的文件
                            images.add(new Image(path, time, name));
58//                        }

**Comment by wj576038874** [comment]
好的 谢谢反馈
